name: Python Lint and Build remote images

on: 
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs: 
  linting: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        
      - run: pip install flake8
      - name: Run flake8 linter
        run: flake8 .  

  docker_build_and_publish:
    needs: linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}


      - name: Build and Push Images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
