name: Python Lint and Build

on: 
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs: 
  linting: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        
      - run: pip install flake8
      - name: Run flake8 linter
        run: flake8 .  

  image: 
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements.txt  
