name: .....sf

on: 
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs: 
  linting: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    - run: pip install flake8
    - run: flake8 / path

  image: 
    - needs: linting
    - runs-on: ubuntu-latest
     