name: Python Lint and Build remote images

on: 
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

permissions:
  packages: write

jobs: 
  linting: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        
      - run: pip install flake8
      - name: Run flake8 linter
        run: flake8 .  

  docker_build_and_publish:
    needs: linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
  
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
  
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          #path: /tmp/.buildx-cache
          push: true
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
  
      - name: Build and Push Images with Docker Compose
        run: |
          docker-compose -f ./Docker_workspace/docker-compose.yml build 
          docker-compose -f ./Docker_workspace/docker-compose.yml push

